/* config.h generated by config_win32.exe. */

/* Uncomment if you want OpenGI to print informative status messages. */
/*#define OPENGI_DEBUG_OUTPUT*/

/* Define to maximum number of simultaneous threads. */
#define OPENGI_MAX_THREADS 1

/* Define to maximum supported SSE version (0, 1, 2 or 3). */
//#define OPENGI_SSE 2
